---
title: "NPPES data summary "

format: 
  docx:
    reference-doc: "D:/PATHWEIGH/custom-reference-doc.docx"

echo: false
---

```{r}
# *****************************************************************************
# Carlos Rodriguez, PhD. CU Anschutz Dept. of Family Medicine.
# nppess_data_summary

# The purpose of this script is to display the columns from the SAS nppes_data 
# file. This file was create by Jake ??? at ACCORDS under the supervision of
# Mark Gritz. The Nppes data contains the designation of FM, IM, or OTHER 
# physician or APP, Gender, and Years since registering an NPI for the
# providers linked to the encounters in the Aim 1 data

# After reviewing data, the goal is to use the provider characteristics in the
# mediation/moderation models of Aim 2. 
# *****************************************************************************
```

```{r}
library(magrittr, include = "%<>%")
pacman::p_load(tidyverse, 
               gtsummary,
               gt)
```

```{r}
# Load SAS data from Jake
data <- haven::read_sas("D:\\PATHWEIGH\\delivery_20240917\\scripts\\aim2\\nppes_data.sas7bdat")
```

# Column names and data types
```{r}
str(data)
```

# Data summary
```{r}
data %>%
  select(-NPI) %>%
  # mutate(YearReg = factor(YearReg),
  #        YearUpdate = factor(YearUpdate)) %>%
  tbl_summary()
```